version: '3'

services:
  portfolio-app:
    build:
      context: .
    container_name: portfolio-app
    restart: always
    ports:
      - 80:8080
    volumes:
      - ./store:/go/src/stock-monitor/store
    environment:
      - "FINNHUB_TOKEN=${FINNHUB_TOKEN}"
      - "EVENT_STREAM_STORAGE_PATH=${EVENT_STREAM_STORAGE_PATH}"
      - "PORTFOLIO_EVENT_STREAM_FILE=${PORTFOLIO_EVENT_STREAM_FILE}"
      - "DIVIDEND_EVENT_STREAM_FILE=${DIVIDEND_EVENT_STREAM_FILE}"
