version: '3'

services:
  portfolio-app:
    build:
      context: .
    container_name: portfolio-app
    restart: always
    ports:
      - 80:8080
    volumes:
      - ./store:/go/src/stock-monitor/store
    environment:
      - "FINNHUB_TOKEN=${FINNHUB_TOKEN}"
